solucaoMaster/Controllers/ClassificadoController.cs
using solucaDomain.Entities.Utilities;
using solucaoData.Repositories;
using solucaoDomain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace solucaoMaster.Controllers
{
    public class ClassificadoController : Controller
    {
        RepositoryClassificado _repositoryClassificado = new RepositoryClassificado();

        private List<ChkTela> chks = new List<ChkTela>();
        // GET: Classificado
        public ActionResult Index()
        {
            var l = _repositoryClassificado.ObterTodos();
            return View(l);
        }

        public ActionResult Detalhes(int id)
        {
            var classificado = _repositoryClassificado.ObterPorID(id);

            return View(classificado);
        }

        public ActionResult Editar(int id)
        {
            var classificado = _repositoryClassificado.ObterPorID(id);

            return View(classificado);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Classificado classificado)
        {
            if (ModelState.IsValid)
            {
                _repositoryClassificado.Atualizar(classificado);
                classificado.Preco = Convert.ToDecimal(classificado.Preco);

                return RedirectToAction("Index");
            }
            
            return View(classificado);
        }

        public ActionResult Deletar() {
            return View();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmado(int id)
        {
            var classificado = _repositoryClassificado.ObterPorID(id);
            _repositoryClassificado.Remover(classificado);
            return RedirectToAction("Index");
        }

        public ActionResult Criar() {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(Classificado classificado) {

            _repositoryClassificado.Adicionar(classificado);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult ObterLista(string json)
        {
            var serializer = new JavaScriptSerializer();
            var model = serializer.Deserialize<List<ChkTela>>(json).ToList();
            chks = model;
            //var model = new JavaScriptSerializer().Deserialize<ChkTela>(json);
            foreach (var item in chks)
            {
                RepositoryClassificado _repositoryClassificado = new RepositoryClassificado();
                var selecionado = _repositoryClassificado.ObterPorID(item.id);
                selecionado.Status = item.valor;
                _repositoryClassificado.Atualizar(selecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

solucaoMaster/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace solucaoMaster.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

solucaoMaster/Views/Classificado/Criar.cshtml
@model solucaoDomain.Entities.Classificado

@{
    ViewBag.Title = "Criar";
}

<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Classificado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

solucaoMaster/Views/Classificado/Deletar.cshtml
@model solucaoDomain.Entities.Classificado

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Classificado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

solucaoMaster/Views/Classificado/Detalhes.cshtml
@model solucaoDomain.Entities.Classificado

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>Classificado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.IDClassificado }) |
    @Html.ActionLink("Voltar", "Index")
</p>

solucaoMaster/Views/Classificado/Editar.cshtml
@model solucaoDomain.Entities.Classificado

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Classificado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDClassificado)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

solucaoMaster/Views/Classificado/Index.cshtml
@model IEnumerable<solucaoDomain.Entities.Classificado>

@{
                /**/

                ViewBag.Title = "Index";
}

<h2>Index</h2>
<div class="row">
    <p>
        @Html.ActionLink("Criar Novo", "Criar")
    </p>
    <p>
        <input type="button" id="btnFinalizar" name="btnFinalizar" value="Finalizar" />
    </p>
</div>


<form>
    <table class="table">
        <tr>
            <th>Título</th>
            <th>Descrição</th>
            <th>Data de Cadastro</th>
            <th>Preço</th>
            <th>Status</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Titulo</td>
                <td>@item.Descricao</td>
                <td>@item.DataCadastro</td>
                <td>@item.Preco</td>
                <td>
                    @*@if (@item.Status)
                    {
                        <input class="chkTela" type="checkbox" value="@item.IDClassificado" checked="checked" />
                    }
                    else
                    {
                        <input class="chkTela" type="checkbox" value="@item.IDClassificado" />
                    }*@

                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.IDClassificado }) |
                    @Html.ActionLink("Detalhes", "Detalhes", new { id = item.IDClassificado }) |
                    @Html.ActionLink("Deletar", "Deletar", new { id = item.IDClassificado })
                </td>
            </tr>
        }

    </table>
</form>
<script>

    //function ObterLista() {

    //    let lista = [];

    //    $('.chkTela').each(function () {

    //        let valordoid = $(this).prop('value');
    //        let valordochk = $(this).prop('checked');

    //        let item = {
    //            id: 0,
    //            valor: false
    //        };

    //        item.id = valordoid;
    //        item.valor = valordochk;

    //        lista.push(item);


    //    });

    //    $.ajax({
    //        type: 'POST',
    //        url: '/Classificado/ObterLista',
    //        data: { json: JSON.stringify(lista) },
    //        dataType: 'text',
    //        success: function (data) {
    //            //alert(data.mensagem);
    //        },
    //        error: function () {
    //            //alert("Erro na tentativa de emissão!");
    //        }
    //    });

    //}
    /*

    //------ lib.js ------
var sqrt = Math.sqrt;
function square(x) {
    return x * x;
}
function diag(x, y) {
    return sqrt(square(x) + square(y));
}
module.exports = {
    sqrt: sqrt,
    square: square,
    diag: diag,
};

//------ main1.js ------
var square = require('lib').square;
var diag = require('lib').diag;

console.log(square(11)); // 121
console.log(diag(4, 3)); // 5

    */

</script>

solucaoMaster/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

solucaoMaster/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("csGOGO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Classificados", "Index", "Classificado")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>